version: "3.9"

x-airflow-common:
  &airflow-common
  build:
    context: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 5
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW_CONN_METADATA_DB: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW_VAR__METADATA_DB_SCHEMA: airflow
    AIRFLOW__CORE__FERNET_KEY: 81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    AIRFLOW__CORE__PARALLELISM: 16
    AIRFLOW__CORE__DAG_CONCURRENCY: 8
    AIRFLOW__API_AUTH__JWT_SECRET: xGjtVAOdYN2W/7Am+krPaYi+4TT3rwPHKNDi4xwSbT8=
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    # Spark connection for Airflow
    AIRFLOW_CONN_SPARK_DEFAULT: 'spark://spark-master:7077'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./config:/opt/airflow/config
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  spark-master:
    container_name: spark-master
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "2g"
    build:
      context: ./Spark
    ports:
      - "7077:7077"   # Spark master
      - "8080:8080"   # Spark master web UI
      - "18080:18080" # Spark history server
    networks:
      - spark-net
    command: sh spark-master.sh
    restart: always

  spark-worker:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "2g"
    build:
      context: ./Spark
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Spark worker web UI
    networks:
      - spark-net
    command: sh spark-worker.sh
    restart: always

  spark-client:
    container_name: spark-client
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "2g"
    build:
      context: ./spark-client
    depends_on:
      - spark-master
    ports:
      - "8888:8888" # Jupyter or custom client
    networks:
      - spark-net
    volumes:
      - ./spark_client/examples:/opt/examples
    restart: always

  minio:
    container_name: minio
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "2g"
    image: "minio/minio:RELEASE.2023-05-04T21-44-30Z"
    volumes:
      - minio:/data
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    networks:
      - spark-net
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - spark-net
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  postgres-spark:
    container_name: postgres-spark
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - spark-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    networks:
      - spark-net
    ports:
      - "8086:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    networks:
      - spark-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 120s
      timeout: 120s
      retries: 3
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    networks:
      - spark-net
    command:
       - -c
       - ls; sh init-airflow.sh; echo "Completed database and user init"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    restart: "no"

volumes:
  minio:
    driver: local
  postgres-db-volume:
  postgres_data:

networks:
  spark-net:
    external: true
